spring:
  application:
    name: StoreScout
  main:
    web-application-type: none
  profiles:
    active: dev
  shell:
    interactive:
      enabled: true  # Use a colon and a space, not an equals sign